name:  🚀 Deploy on push using ssh

on:
  push:
    branches:
      - release

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Deploy using ssh
#       uses: appleboy/ssh-action@master
#       with:
#         host: ${{ secrets.HOST }}
#         username: ${{ secrets.USERNAME }}
#         key: ${{ secrets.PRIVATE_KEY }}
#         port: 22
#         script: |
#           eval $(ssh-agent)
#           sleep 2
#           ssh-add ~/.ssh/git
#           cd /opt/smart-campus
#           git pull origin release
#           git status
#           yarn install
#           yarn build
#           pm2 restart smart_api
#           pm2 restart smart_web